name: rikulo_security
version: 0.5.1
description: > 
  A lightweight and highly customizable authentication and access-control framework for Rikulo Stream.
authors:
- Tom Yeh <tomyeh@rikulo.org>
homepage: http://rikulo.org/projects/stream
dependencies:
  stream: any
  meta: any
