name: rikulo_security
version: 0.5.6
description: > 
  A lightweight and highly customizable authentication and access-control framework for Rikulo Stream.
authors:
- Tom Yeh <tomyeh@rikulo.org>
homepage: http://rikulo.org/projects/stream
documentation: http://docs.rikulo.org/stream/latest/Add-ons/Rikulo_Security/
dependencies:
  stream: any
  meta: any
